name: Auto-close Awaiting Response Issues

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
permissions:
  issues: write
jobs:
  close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close inactive issues with awaiting-response label
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'awaiting-response'
            });

            const now = new Date();

            for (const issue of issues.data) {
              const events = await github.rest.issues.listEvents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number
              });

              const lastCommentTime = new Date(issue.updated_at);
              const diffMinutes = (now - lastCommentTime) / 1000 / 60;

              if (diffMinutes > 2) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'Issue automatically closed due to inactivity after awaiting response.'
                });

                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
              }
            }
