name: Mark issue as awaiting response on comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  repository-projects: write

jobs:
  mark_awaiting:
    runs-on: ubuntu-latest
    steps:
      - name: Add awaiting-response label
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              labels: ['awaiting-response']
            });

      - name: Move issue to Awaiting response in project
        uses: peter-evans/create-or-update-project-card@v3
        with:
          project-name: 'Kanban1' # Replace with your project name
          column-name: 'Awaiting Response' # Replace if your column/status name differs
          issue-number: ${{ github.event.issue.number }}
